### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by adokitkat** [donn/nudelta#6]
Hello, since this is already running on Linux and MacOS, and is written in C++ and Python, I think Windows build would be appropriate even if there already original Nuphy Console on Windows. I can imagine many would like to use an open-source alternative.

Also off-topic, but I have both Air75 and Air60, so if there is a way I can help you I can - I would like to use this on my Air60 too :)

**Comment by donn** [comment]
Hi, thank you for your interest- I'll take a look at Windows builds, I really only foresee two issues:

1. I've honestly never tried building Node.js native extensions on Windows, so that's gonna be fun. (Python is only used for build scripts and is relatively straightforward)
2. I'm not sure what Win32's USB permissions model is. I guess worst-case scenario I can just ask people to run Nudelta as Administrator but frankly, running userspace apps as Admin is something I don't entirely want to encourage.

But I believe it's probably doable.

---
Thank you for offering to help with the Air60 thing, let's continue that on Discord.

**Comment by donn** [comment]
Just so you're in the loop, I gave compiling for Windows a shot: there... seems to be a crash when it tries to read from the keyboard. Not sure why.

I'm gonna need to debug it, but that involves compiling with the clang toolchain so I can use lldb. Anyways, that's not gonna happen this week, I'm too busy.
